<a href="https://colab.research.google.com/github/utsabsarkar12/Deep_Learning/blob/main/Activation_Functions_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

## 1. ReLU - Rectified Linear Unit (Hidden Layer)

In [4]:
def relu(x):
  return np.maximum(0, x)

In [5]:
relu(-120)

np.int64(0)

In [6]:
relu(12)

np.int64(12)

In [7]:
relu(np.array([-1, 2,-3,1]))

array([0, 2, 0, 1])

## 2. Leaky ReLU (Hidden Layer)

In [8]:
def leaky_relu(x, alpha=0.01):
  return np.maximum(alpha*x, x)

In [9]:
leaky_relu(120)

np.float64(120.0)

In [10]:
leaky_relu(-1)

np.float64(-0.01)

## 3. Sigmoid (Output Layer & Binaryclass Problem)

In [11]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [12]:
sigmoid(12)

np.float64(0.9999938558253978)

In [13]:
sigmoid(np.array([1,2,3]))

array([0.73105858, 0.88079708, 0.95257413])

## 4. Softmax (Output Layer & Multiclass Problem)

In [15]:
def softmax(x):
  e_x = np.exp(x - np.max(x))
  return e_x/e_x.sum(axis = 0)

In [18]:
proba = softmax(np.array([4,2,3]))
proba

array([0.66524096, 0.09003057, 0.24472847])

In [19]:
sum(proba)

np.float64(0.9999999999999999)